# This runs jobs which pyiron modules should run on pushes or PRs to main

name: Push-Pull

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pyiron:
    uses: pyiron/actions/.github/workflows/push-pull.yml@actions-3.1.0
    secrets: inherit
    with:
      do-unit-tests: false
      do-codacy: false
      do-benchmark-tests: false
      notebooks-env-files: .ci_support/environment.yml .ci_support/environment-jnmpi_nodes.yml